# Generated by Django 5.0.6 on 2024-05-28 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='questionario_app.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario_app.escolha')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario_app.questao')),
            ],
        ),
    ]
