# Generated by Django 5.0.6 on 2024-05-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='resposta_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='escolha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionario_app.escolha'),
        ),
    ]
